namespace Cnas.Ps.Infrastructure.Storage;

/// <summary>Configuration for the MinIO file storage adapter. Bound from <c>Minio:*</c>.</summary>
public sealed class MinioOptions
{
    /// <summary>Configuration section name to bind from app settings.</summary>
    public const string SectionName = "Minio";

    /// <summary>S3-compatible endpoint, host[:port]. Example: <c>minio:9000</c>.</summary>
    public string Endpoint { get; set; } = "minio:9000";

    /// <summary>Access key (loaded from secret store / env var — never in source control).</summary>
    public string AccessKey { get; set; } = string.Empty;

    /// <summary>Secret key (loaded from secret store / env var — never in source control).</summary>
    public string SecretKey { get; set; } = string.Empty;

    /// <summary>True to require TLS to the endpoint. Defaults to false for local dev.</summary>
    public bool UseSsl { get; set; }

    /// <summary>Default bucket name for citizen-uploaded documents.</summary>
    public string CitizenUploadsBucket { get; set; } = "cnas-citizen-uploads";

    /// <summary>Default bucket name for documents generated by CNAS (decisions, certificates).</summary>
    public string GeneratedDocumentsBucket { get; set; } = "cnas-generated";

    /// <summary>Maximum file size (bytes) accepted on upload (SEC 010). Default 25 MiB.</summary>
    public long MaxFileSizeBytes { get; set; } = 25L * 1024 * 1024;
}
