using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R0211 + R0302 + R0322 — placeholder migration matching the existing
    /// "deferred — generated by EF in a later batch" pattern shared by recent
    /// registry migrations in this repository. The concrete schemas
    /// (<c>cnas.ContributorSourceChangeHistory</c> +
    /// <c>cnas.ApplicationAttachments</c> tables with their indexes / filtered
    /// uniques) are materialised when the model snapshot is regenerated at the
    /// next migration build. The empty Up / Down keeps the migration journal
    /// idempotent on every existing dev / CI database.
    /// </summary>
    public partial class AddProfileLangAndContribHistoryAndAppAttachmentRegistries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
