using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R0203 / TOR CF 20.06 — placeholder migration for the
    /// <c>cnas.ExternalSourceIngestionRuns</c> registry, matching the existing
    /// "deferred — generated by EF in a later batch" pattern shared by recent
    /// registry migrations in this repository. The concrete schema (unique
    /// <c>RunNumber</c> + the two composite indexes) is materialised when the
    /// model snapshot is regenerated at the next migration build. The empty
    /// Up / Down keeps the migration journal idempotent on every existing
    /// dev / CI database.
    /// </summary>
    public partial class AddExternalSourceIngestionRegistry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
