using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R0027 / TOR ARH 022 — placeholder migration for the additive
    /// per-locale display-name columns introduced in iter-122:
    /// <list type="bullet">
    ///   <item><c>cnas.CnasBranches.NameRo / NameRu / NameEn</c> (nullable string, 256)</item>
    ///   <item><c>cnas.SupportTicketCategories.NameRo / NameRu / NameEn</c> (nullable string, 256)</item>
    ///   <item><c>cnas.AuditCategories.NameRo / NameRu / NameEn</c> (nullable string, 256)</item>
    /// </list>
    /// Matches the existing "deferred — generated by EF in a later batch" pattern shared
    /// by recent additive-column migrations (e.g.
    /// <c>20260524130000_AddTemplateValidationAndPassportMatrixColumns</c>). The concrete
    /// schema is materialised when the model snapshot is regenerated at the next migration
    /// build; empty Up / Down keeps the migration journal idempotent on every existing
    /// dev / CI database. All nine columns are nullable so legacy rows behave unchanged —
    /// callers fall back to <c>Name</c> / <c>DisplayName</c> via
    /// <c>Cnas.Ps.Application.Localization.ILocalizedNameResolver</c>.
    /// </summary>
    public partial class AddLocalizedNameColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
