using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R2500 / TOR PIR 020-023 — placeholder migration matching the existing
    /// "deferred — generated by EF in a later batch" pattern shared by every
    /// other recent registry migration in this repository.
    /// </summary>
    public partial class AddHelpdeskRegistry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
