using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R0131 + R0143 / CF 17.15 + CF 17.19 — placeholder migration for the additive
    /// columns introduced in iter-121:
    /// <list type="bullet">
    ///   <item><c>cnas.DocumentTemplates.ValidationRulesJson</c> (nullable jsonb)</item>
    ///   <item><c>cnas.ServicePassports.MandatoryAttachmentsJson</c> (nullable jsonb)</item>
    ///   <item><c>cnas.ServicePassports.CalcFormulasJson</c> (nullable jsonb)</item>
    /// </list>
    /// Matches the existing "deferred — generated by EF in a later batch" pattern shared
    /// by recent additive-column migrations (see e.g.
    /// <c>20260524120000_AddNotificationRelatedEntityColumns</c>). The concrete schema
    /// is materialised when the model snapshot is regenerated at the next migration
    /// build; empty Up / Down keeps the migration journal idempotent on every existing
    /// dev / CI database. All three columns are nullable so legacy rows behave unchanged.
    /// </summary>
    public partial class AddTemplateValidationAndPassportMatrixColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
