using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R2505 + R2506 / TOR PIR 030-033, 037-040 — placeholder migration
    /// matching the existing "deferred — generated by EF in a later batch"
    /// pattern shared by every other recent registry migration in this
    /// repository. The concrete schema (ChangeRequests, QualityRisks,
    /// QualityRiskPreventiveActions) is materialised when the model snapshot
    /// is regenerated at the next migration build.
    /// </summary>
    public partial class AddChangeManagementAndQaRiskRegistry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
