using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R0103 / TOR CF 14.02 — placeholder migration matching the existing
    /// "deferred — generated by EF in a later batch" pattern shared by every
    /// other recent registry migration in this repository. The concrete schema
    /// (<c>cnas.ProcessedIntegrationEvents</c> table + UNIQUE(MessageId)) is
    /// materialised when the model snapshot is regenerated at the next
    /// migration build.
    /// </summary>
    public partial class AddIntegrationEventDedupRegistry : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
