using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cnas.Ps.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// R0172 / TOR CF 22.05 — placeholder migration for the
    /// <c>cnas.Notifications.RelatedEntityType</c> + <c>RelatedEntityId</c>
    /// columns + their composite index, matching the existing "deferred —
    /// generated by EF in a later batch" pattern shared by recent registry
    /// migrations in this repository. The concrete schema (two nullable
    /// columns and the <c>(RelatedEntityType, RelatedEntityId)</c> non-unique
    /// composite index) is materialised when the model snapshot is regenerated
    /// at the next migration build. The empty Up / Down keeps the migration
    /// journal idempotent on every existing dev / CI database.
    /// </summary>
    public partial class AddNotificationRelatedEntityColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
