using Cnas.Ps.Contracts.Security;

namespace Cnas.Ps.Contracts;

/// <summary>
/// R0153 / TOR CF 19.05 — public projection of a single
/// <c>Cnas.Ps.Core.Domain.ContributorPeriodProjection</c> row. One DTO per
/// slice; reports issue a single <c>WHERE PeriodStartUtc &lt;= asOf &amp;&amp;
/// asOf &lt; PeriodEndUtc</c> against the projection table to resolve
/// "what was the state as-of date X?" without scanning the source
/// supersession chains.
/// </summary>
/// <param name="Id">
/// Sqid-encoded surrogate id of the projection row. Opaque to clients per
/// CLAUDE.md RULE 3.
/// </param>
/// <param name="ContributorSqid">
/// Sqid-encoded id of the <c>InsuredPerson</c> ("Persoană asigurată") the
/// slice belongs to.
/// </param>
/// <param name="PeriodStartUtc">
/// Inclusive UTC start of the slice. Together with
/// <paramref name="PeriodEndUtc"/> describes the half-open interval the
/// projected values were valid for.
/// </param>
/// <param name="PeriodEndUtc">
/// Exclusive UTC end of the slice. Equal to <c>DateTime.MaxValue</c> when
/// the underlying source row is open-ended (still current).
/// </param>
/// <param name="CivilStatus">
/// Stable string code of the contributor's civil status during the slice
/// (e.g. <c>"Single"</c>, <c>"Married"</c>). Null when no civil-status row
/// covered the slice midpoint.
/// </param>
/// <param name="CurrentEmployerCode">
/// Employer-code string for the activity period covering the slice. Null
/// when no activity period covered the slice midpoint.
/// </param>
/// <param name="MonthlySalary">
/// Monthly salary at the covering activity period (MDL). Null when no
/// activity period covered the slice OR when the source row did not record
/// a salary.
/// </param>
/// <param name="AddressCity">City from the covering address row.</param>
/// <param name="AddressRegion">Region (raion / county) from the covering address row.</param>
/// <param name="AddressCountry">ISO-3166-1 alpha-2 country code from the covering address row.</param>
/// <param name="PhoneE164">
/// Phone in E.164 format from the covering contact row. Carries the
/// <see cref="SensitivityLabel.Confidential"/> classification per R0228.
/// </param>
/// <param name="Email">
/// Email from the covering contact row. Carries the
/// <see cref="SensitivityLabel.Confidential"/> classification per R0228.
/// </param>
/// <param name="ProjectedAtUtc">
/// UTC instant at which this row was generated by the
/// <c>ContributorPeriodProjectionService</c>. Surfaced for operator
/// observability.
/// </param>
public sealed record ContributorPeriodProjectionDto(
    string Id,
    string ContributorSqid,
    DateTime PeriodStartUtc,
    DateTime PeriodEndUtc,
    [property: SensitivityClassification(SensitivityLabel.Confidential,
        Reason = "CivilStatus is citizen PII per R0228 / SEC 033.")]
    string? CivilStatus,
    [property: SensitivityClassification(SensitivityLabel.Confidential,
        Reason = "CurrentEmployerCode reveals the citizen's employer relationship per R0228 / SEC 033.")]
    string? CurrentEmployerCode,
    [property: SensitivityClassification(SensitivityLabel.Confidential,
        Reason = "MonthlySalary is personal-finance PII per R0228 / SEC 033.")]
    decimal? MonthlySalary,
    [property: SensitivityClassification(SensitivityLabel.Confidential,
        Reason = "AddressCity is citizen address PII per R0228 / SEC 033.")]
    string? AddressCity,
    [property: SensitivityClassification(SensitivityLabel.Confidential,
        Reason = "AddressRegion is citizen address PII per R0228 / SEC 033.")]
    string? AddressRegion,
    [property: SensitivityClassification(SensitivityLabel.Confidential,
        Reason = "AddressCountry is citizen address PII per R0228 / SEC 033.")]
    string? AddressCountry,
    [property: SensitivityClassification(SensitivityLabel.Confidential)]
    string? PhoneE164,
    [property: SensitivityClassification(SensitivityLabel.Confidential)]
    string? Email,
    DateTime ProjectedAtUtc);

/// <summary>
/// R0153 / TOR CF 19.05 — summary of a single
/// <c>IContributorPeriodProjectionService</c> run. Returned by both the
/// per-contributor rebuild endpoint and the batch endpoint; batch runs leave
/// <see cref="ContributorSqid"/> null because no single contributor is the
/// subject.
/// </summary>
/// <param name="ContributorSqid">
/// Sqid-encoded id of the contributor the run rebuilt; <c>null</c> for the
/// batch (<c>RebuildAllAsync</c>) variant.
/// </param>
/// <param name="SlicesCreated">
/// Count of <c>ContributorPeriodProjection</c> rows inserted by the run.
/// Equal to the count after the idempotent DELETE-then-INSERT cycle.
/// </param>
/// <param name="ContributorsProcessed">
/// Count of contributors the run touched. <c>1</c> for the per-contributor
/// endpoint, >= 0 for the batch endpoint.
/// </param>
/// <param name="DurationMs">
/// Wall-clock duration of the run, in whole milliseconds, including the
/// final <c>SaveChangesAsync</c>. Surfaced for operator observability.
/// </param>
public sealed record ContributorPeriodProjectionRunDto(
    string? ContributorSqid,
    int SlicesCreated,
    int ContributorsProcessed,
    long DurationMs);
