namespace Cnas.Ps.Contracts;

/// <summary>
/// Sqid identifiers of the two draft documents generated by the examiner workflow
/// when the system auto-produces a Fișa de calcul (calculation sheet) and a Decizia
/// (decision document) for a dossier. UC08.04.
/// </summary>
/// <param name="CalculationSheetId">Sqid-encoded id of the Fișa de calcul document row.</param>
/// <param name="DecisionId">Sqid-encoded id of the Decizia document row.</param>
/// <example>
/// <code>
/// var result = await examination.GenerateDraftsAsync(dossierSqid);
/// if (result.IsSuccess)
/// {
///     Console.WriteLine(result.Value.CalculationSheetId); // e.g. "k3Gq9"
///     Console.WriteLine(result.Value.DecisionId);         // e.g. "Xm7Yz3"
/// }
/// </code>
/// </example>
public sealed record DraftDocumentsResult(string CalculationSheetId, string DecisionId);

/// <summary>
/// R0573 / TOR CF 08.05 — payload for <c>POST /api/examination/dossiers/{sqid}/emit-decision</c>.
/// The examiner picks an Annex 7 decision template by its stable kebab-case
/// <c>TemplateCode</c> (e.g. <c>decizia-pensie</c>, <c>refuz-aplicare</c>,
/// <c>decizie-revocare</c>) and optionally attaches a free-text note and
/// override amount. The service re-renders the decision document, persists a
/// new <c>Document</c> row, and notifies the
/// solicitant.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why a separate endpoint?</b> The verdict endpoint
/// (<c>POST .../documents/{id}/verdict</c>) records an examiner verdict on an
/// existing attached document. The emit-decision endpoint produces a brand-new
/// decision document anchored to the dossier — distinct semantics, distinct
/// audit code (<c>EXAMINATION.NEW_DECISION_EMITTED</c>).
/// </para>
/// <para>
/// <b>Editable-state guard.</b> The service refuses to emit a new decision when
/// the parent application has already reached a terminal status (Approved /
/// Rejected / Closed / Withdrawn) and surfaces <c>EXAMINATION.NOT_EDITABLE</c>.
/// </para>
/// <para>
/// <b>Sqid invariant.</b> The wire envelope carries no raw database identifiers
/// — the dossier sqid is supplied in the URL path, not the body (CLAUDE.md
/// RULE 3).
/// </para>
/// </remarks>
/// <param name="DecisionTemplateCode">
/// Stable kebab-case Annex 7 template code (case-insensitive match against the
/// registered <c>IDocxTemplate</c> implementations). 3-64 chars. Examples:
/// <c>decizia-pensie</c>, <c>refuz-aplicare</c>, <c>decizie-revocare</c>.
/// </param>
/// <param name="Notes">
/// Optional free-text note recorded on the audit row. ≤ 1000 chars. Captured
/// verbatim — the examiner is responsible for redacting any PII inappropriate
/// for the audit trail.
/// </param>
/// <param name="OverrideAmount">
/// Optional override of the decision-engine computed amount, in MDL. When
/// supplied the value must be > 0 (negative or zero overrides are operator
/// errors). When null (default) the engine outcome on the dossier is used
/// verbatim.
/// </param>
public sealed record EmitNewDecisionInputDto(
    string DecisionTemplateCode,
    string? Notes = null,
    decimal? OverrideAmount = null);

/// <summary>
/// R0573 / TOR CF 08.05 — outbound projection of a freshly-emitted decision
/// document. Carries the Sqid id of the new <c>Document</c> row and a copy of
/// the decision-template code so the UI can render an immediate preview link
/// without a follow-up round trip.
/// </summary>
/// <param name="DocumentId">
/// Sqid-encoded id of the new <c>Document</c> row. Use this to fetch the
/// rendered bytes through the documents controller.
/// </param>
/// <param name="DecisionTemplateCode">
/// Echo of the template code the examiner picked, normalised to lower case.
/// </param>
public sealed record EmittedDecisionDto(
    string DocumentId,
    string DecisionTemplateCode);
