namespace Cnas.Ps.Core.Domain;

/// <summary>
/// R1403 / TOR §3.6-D — one lifetime athlete-pension award decision aggregate
/// (indemnizație viageră sportivi performanță + antrenori). The award is
/// granted to high-performance athletes who meet medal-threshold criteria
/// after retirement age, and to the coaches who trained such athletes after a
/// minimum years-of-service threshold.
/// </summary>
/// <remarks>
/// <para>
/// <b>Lifecycle.</b> <see cref="AthletePensionAwardStatus.Draft"/> →
/// <see cref="AthletePensionAwardStatus.Submitted"/> →
/// <see cref="AthletePensionAwardStatus.Approved"/> / <see cref="AthletePensionAwardStatus.Rejected"/>;
/// from <c>Approved</c> the operator drives to
/// <see cref="AthletePensionAwardStatus.Active"/>, then optionally
/// <see cref="AthletePensionAwardStatus.Suspended"/> / resume; the row
/// terminates via <see cref="AthletePensionAwardStatus.Terminated"/>.
/// <c>Rejected</c> and <c>Terminated</c> are terminal.
/// </para>
/// <para>
/// <b>Encrypted column.</b> <see cref="BeneficiaryIdnp"/> is encrypted at
/// rest via <c>EncryptedStringConverter</c> (CLAUDE.md §5.7). Equality
/// lookups go through the deterministic HMAC shadow column
/// <see cref="BeneficiaryIdnpHash"/>.
/// </para>
/// <para>
/// <b>External id.</b> Implements <see cref="IExternalId"/> because the
/// outbound DTO carries a Sqid-encoded surrogate per CLAUDE.md RULE 3.
/// </para>
/// <para>
/// <b>Placeholder semantics.</b> The eligibility thresholds and the
/// multiplier table snapshotted on this row are PLACEHOLDER values pending
/// the regulatory load — see the in-Infrastructure evaluator + calculator
/// remarks for the canonical authority chain.
/// </para>
/// </remarks>
public sealed class AthletePensionAward : AuditableEntity, IExternalId
{
    /// <summary>
    /// Stable external identifier of the award, auto-generated by the service
    /// in the format <c>APE-{year}-{seq:000000}</c>. Unique across the registry;
    /// capped at 32 characters at the persistence layer.
    /// </summary>
    public required string AwardNumber { get; set; }

    /// <summary>
    /// Moldovan personal-numeric-identifier (IDNP, 13 digits) of the
    /// beneficiary athlete or coach. Encrypted at rest per CLAUDE.md §5.7;
    /// equality lookups go through <see cref="BeneficiaryIdnpHash"/>.
    /// </summary>
    public required string BeneficiaryIdnp { get; set; }

    /// <summary>
    /// Base64-encoded HMAC-SHA256 hash of the canonicalised
    /// <see cref="BeneficiaryIdnp"/> (44 chars including <c>=</c> padding).
    /// Backs equality lookups and the duplicate-detection index. Maintained by
    /// the application layer via <c>IDeterministicHasher</c>.
    /// </summary>
    public required string BeneficiaryIdnpHash { get; set; }

    /// <summary>
    /// Display name of the beneficiary (3..256 chars). Stored as plaintext
    /// (it is already widely known for medal-winning athletes); audit
    /// payloads still never embed it.
    /// </summary>
    public required string BeneficiaryDisplayName { get; set; }

    /// <summary>Beneficiary date of birth — drives retirement-age and minimum-age checks.</summary>
    public DateOnly BeneficiaryBirthDate { get; set; }

    /// <summary>Beneficiary biological sex — kept for demographic reporting only.</summary>
    public BeneficiarySex BeneficiarySex { get; set; }

    /// <summary>Role under which the award is granted — athlete or coach.</summary>
    public AthletePensionRole Role { get; set; }

    /// <summary>
    /// Stable sport-discipline code from a controlled vocabulary (e.g.
    /// <c>ATHLETICS</c>, <c>BOXING</c>, <c>WRESTLING_FREESTYLE</c>). Capped at
    /// 128 chars; validated against the regex <c>^[A-Z][A-Z0-9_]{1,127}$</c>.
    /// </summary>
    public required string SportDiscipline { get; set; }

    /// <summary>Lifecycle status. Drives the state-machine guard at every service entry point.</summary>
    public AthletePensionAwardStatus Status { get; set; } = AthletePensionAwardStatus.Draft;

    /// <summary>UTC timestamp the award was requested (mirror of <c>CreatedAtUtc</c> for explicit naming).</summary>
    public DateTime RequestedAt { get; set; }

    /// <summary>UTC timestamp the award was approved; <c>null</c> until approval.</summary>
    public DateTime? ApprovedAt { get; set; }

    /// <summary>UTC timestamp the award was rejected; <c>null</c> until rejection.</summary>
    public DateTime? RejectedAt { get; set; }

    /// <summary>
    /// Operator-supplied rationale recorded when the award transitions to
    /// <see cref="AthletePensionAwardStatus.Rejected"/> (3..1000 chars; null otherwise).
    /// </summary>
    public string? RejectionReason { get; set; }

    /// <summary>
    /// Calendar date from which the monthly pension starts to accrue.
    /// Populated when the row enters <see cref="AthletePensionAwardStatus.Active"/>.
    /// </summary>
    public DateOnly? EffectiveFrom { get; set; }

    /// <summary>UTC timestamp the award was suspended; <c>null</c> when not suspended.</summary>
    public DateTime? SuspendedAt { get; set; }

    /// <summary>
    /// Operator-supplied rationale recorded when the award transitions to
    /// <see cref="AthletePensionAwardStatus.Suspended"/> (3..1000 chars; null otherwise).
    /// </summary>
    public string? SuspensionReason { get; set; }

    /// <summary>UTC timestamp the award was terminated; <c>null</c> when not terminated.</summary>
    public DateTime? TerminatedAt { get; set; }

    /// <summary>
    /// Operator-supplied rationale recorded when the award transitions to
    /// <see cref="AthletePensionAwardStatus.Terminated"/> (3..1000 chars; null otherwise).
    /// </summary>
    public string? TerminationReason { get; set; }

    /// <summary>
    /// Monthly pension amount in MDL. Zero until <see cref="AthletePensionAwardStatus.Approved"/>;
    /// thereafter constrained to <c>(0, 100_000_000]</c> at the validator.
    /// Treated as Confidential at the contracts layer.
    /// </summary>
    public decimal MonthlyAmountMdl { get; set; }

    /// <summary>
    /// Snapshot of the regulatory base amount (MDL) used at approval time.
    /// Recorded for explainability and future-recalc audit — changing the
    /// regulatory base afterwards must not retroactively recompute the row
    /// without an explicit recalc event.
    /// </summary>
    public decimal RegulatoryBaseMdl { get; set; }

    /// <summary>
    /// Snapshot of the final multiplier (in percent, e.g. <c>250</c> = 250%)
    /// applied to <see cref="RegulatoryBaseMdl"/> at approval time. Encodes
    /// the combined base-medal multiplier + coach factor + any
    /// admin-supplied additional multipliers.
    /// </summary>
    public decimal MultiplierPercent { get; set; }

    /// <summary>
    /// JSON-encoded eligibility-evaluator reasoning trace (per-rule hits +
    /// per-record contributions). NEVER embeds the beneficiary IDNP or
    /// display name — only enum-name codes and numeric values.
    /// </summary>
    public string? EligibilityNotesJson { get; set; }

    /// <summary>FK to the <see cref="UserProfile"/> who registered the award.</summary>
    public int RegisteredByUserId { get; set; }

    /// <summary>UTC timestamp of the last amount recomputation, when applicable.</summary>
    public DateTime? LastRecomputedAt { get; set; }
}
