namespace Cnas.Ps.Core.Domain;

/// <summary>
/// R1202 / TOR §3.4-C — one capitalised-payment request (cerere de capitalizare
/// a plăților periodice). Opened by a CNAS operator when notified that a
/// Moldovan company is being liquidated and that company owes an ongoing
/// periodic indemnization obligation (incapacity-for-work / loss-of-breadwinner
/// / occupational-disease) to a former employee. The request drives the
/// computation of a single capitalised lump sum (present value of the future
/// stream) which the liquidator pays to CNAS; CNAS thereafter takes over the
/// monthly disbursement from the capitalised funds.
/// </summary>
/// <remarks>
/// <para>
/// <b>Lifecycle.</b> <see cref="CapitalisedPaymentRequestStatus.Draft"/> →
/// <see cref="CapitalisedPaymentRequestStatus.Submitted"/> →
/// <see cref="CapitalisedPaymentRequestStatus.Computing"/> →
/// <see cref="CapitalisedPaymentRequestStatus.ComputedAwaitingApproval"/> →
/// <see cref="CapitalisedPaymentRequestStatus.Approved"/> →
/// <see cref="CapitalisedPaymentRequestStatus.Settled"/>. From any non-terminal
/// stage the operator may issue
/// <see cref="CapitalisedPaymentRequestStatus.Cancelled"/> with an explicit
/// rationale. <see cref="CapitalisedPaymentRequestStatus.Rejected"/>,
/// <see cref="CapitalisedPaymentRequestStatus.Cancelled"/>, and
/// <see cref="CapitalisedPaymentRequestStatus.Settled"/> are terminal.
/// </para>
/// <para>
/// <b>Encrypted columns.</b> The beneficiary IDNP and the liquidated-debtor
/// IDNO are PII / business-sensitive and are encrypted at rest via
/// <c>EncryptedStringConverter</c> (CLAUDE.md §5.7). Equality lookups against
/// the plaintext are unsupported; callers query through the deterministic
/// HMAC shadow columns <see cref="BeneficiaryIdnpHash"/> /
/// <see cref="LiquidatedDebtorIdnoHash"/>.
/// </para>
/// <para>
/// <b>External id.</b> Implements <see cref="IExternalId"/> because the
/// outbound DTO carries a Sqid-encoded surrogate per CLAUDE.md RULE 3.
/// </para>
/// </remarks>
public sealed class CapitalisedPaymentRequest : AuditableEntity, IExternalId
{
    /// <summary>
    /// Stable external identifier of the request, auto-generated by the service
    /// in the format <c>CPR-{year}-{seq:000000}</c>. Unique across the registry;
    /// capped at 32 characters at the persistence layer.
    /// </summary>
    public required string RequestNumber { get; set; }

    /// <summary>
    /// Moldovan personal-numeric-identifier (IDNP, 13 digits) of the
    /// beneficiary whose monthly indemnity is being capitalised. Encrypted at
    /// rest per CLAUDE.md §5.7; equality lookups go through
    /// <see cref="BeneficiaryIdnpHash"/>.
    /// </summary>
    public required string BeneficiaryIdnp { get; set; }

    /// <summary>
    /// Base64-encoded HMAC-SHA256 hash of the canonicalised
    /// <see cref="BeneficiaryIdnp"/> (44 chars including <c>=</c> padding).
    /// Backs equality lookups and the duplicate-detection index. Maintained by
    /// the application layer — every site that writes the plaintext MUST also
    /// write this column via <c>IDeterministicHasher.ComputeHash</c>.
    /// </summary>
    public required string BeneficiaryIdnpHash { get; set; }

    /// <summary>
    /// Beneficiary date of birth (calendar date). Used to compute the
    /// beneficiary's age at <see cref="ValuationDate"/>, which in turn drives
    /// the mortality-table lookup. Must be in the past.
    /// </summary>
    public DateOnly BeneficiaryBirthDate { get; set; }

    /// <summary>Beneficiary biological sex — drives the mortality-table lookup column.</summary>
    public BeneficiarySex BeneficiarySex { get; set; }

    /// <summary>
    /// IDNO (Moldovan fiscal-code, 13 digits) of the liquidated debtor company.
    /// Encrypted at rest; equality lookups go through
    /// <see cref="LiquidatedDebtorIdnoHash"/>.
    /// </summary>
    public required string LiquidatedDebtorIdno { get; set; }

    /// <summary>
    /// Base64-encoded HMAC-SHA256 hash of the canonicalised
    /// <see cref="LiquidatedDebtorIdno"/>. Backs equality lookups and the
    /// duplicate-detection index.
    /// </summary>
    public required string LiquidatedDebtorIdnoHash { get; set; }

    /// <summary>Display name of the liquidated debtor (3..256 chars).</summary>
    public required string LiquidatedDebtorName { get; set; }

    /// <summary>Lifecycle status. Drives the state-machine guard at every service entry point.</summary>
    public CapitalisedPaymentRequestStatus Status { get; set; } = CapitalisedPaymentRequestStatus.Draft;

    /// <summary>Kind of periodic obligation being capitalised.</summary>
    public CapitalisedPaymentObligationKind ObligationKind { get; set; }

    /// <summary>
    /// Current monthly indemnity amount (MDL) that is being capitalised.
    /// 2-decimal precision; constrained to <c>(0, 100_000_000]</c> at the
    /// validator. Treated as Confidential at the contracts layer.
    /// </summary>
    public decimal MonthlyAmountMdl { get; set; }

    /// <summary>First month in which the periodic indemnity ran.</summary>
    public DateOnly ObligationStartDate { get; set; }

    /// <summary>
    /// Last month in which the periodic indemnity must run, or <c>null</c> when
    /// the obligation is lifetime (then mortality table drives N).
    /// </summary>
    public DateOnly? ObligationEndDate { get; set; }

    /// <summary>
    /// Date as of which the present value is computed. Cut-off
    /// <c>[today - 7d, today + 365d]</c> enforced by the validator (clock
    /// abstracted via <c>ICnasTimeProvider</c>).
    /// </summary>
    public DateOnly ValuationDate { get; set; }

    /// <summary>
    /// Annual legal discount rate (%). 4-decimal precision; constrained to
    /// <c>[0, 30]</c> at the validator. Converted to a monthly compounded
    /// effective rate inside the calculator.
    /// </summary>
    public decimal LegalDiscountRatePercent { get; set; }

    /// <summary>FK to the <see cref="UserProfile"/> who registered the request.</summary>
    public int RegisteredByUserId { get; set; }

    /// <summary>
    /// Operator-supplied rationale recorded when the request transitions to
    /// <see cref="CapitalisedPaymentRequestStatus.Cancelled"/> (3..1000 chars
    /// when set; null otherwise).
    /// </summary>
    public string? CancellationReason { get; set; }
}
