using Cnas.Ps.Core.Audit;

namespace Cnas.Ps.Core.Domain;

/// <summary>
/// R0831 / TOR BP 1.3-B — a claim (creanță) is an outstanding debt that a
/// contributor owes CNAS (unpaid contribution principal, late penalty,
/// adjusted-amount differential, court order, audit-control assessment, etc.).
/// One row exists per outstanding obligation; partial payments accumulate via
/// <see cref="ClaimPayment"/> children and update <see cref="PaidAmount"/> /
/// <see cref="RemainingAmount"/> / <see cref="Status"/>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Lifecycle.</b> Claims land in <see cref="ClaimStatus.Open"/> on registration.
/// A first partial payment flips the row to
/// <see cref="ClaimStatus.PartiallyPaid"/>; the payment that drives the running
/// total to <see cref="PrincipalAmount"/> flips the row to
/// <see cref="ClaimStatus.Settled"/> and stamps <see cref="SettledDate"/>. An
/// admin can <see cref="ClaimStatus.Cancelled"/> a still-outstanding claim with
/// a rationale or transition it to <see cref="ClaimStatus.Disputed"/> while a
/// contributor contests the obligation. Cancellation is terminal; modifying or
/// adding payments to a Settled or Cancelled claim is refused.
/// </para>
/// <para>
/// <b>Natural-key uniqueness.</b> <see cref="ClaimNumber"/> is an external
/// stable identifier auto-generated by the service in the format
/// <c>CRN-{year}-{seq:000000}</c>. Operators reference claims by this number
/// in citizen correspondence and audit reports.
/// </para>
/// <para>
/// <b>External id.</b> The entity implements <see cref="IExternalId"/> because
/// the outbound DTO (<c>Cnas.Ps.Contracts.ClaimDto.Id</c>) carries a
/// Sqid-encoded surrogate per CLAUDE.md RULE 3.
/// </para>
/// <para>
/// <b>Deferred work.</b> Auto-creation of claims from R0819 late-penalty rows
/// is intentionally NOT done in this iteration — operators register claims
/// manually based on the calculated penalty figures. A future iteration will
/// add an idempotent projector that creates <see cref="Claim"/> rows for any
/// non-zero penalty whose principal is still unpaid.
/// </para>
/// </remarks>
public sealed class Claim : AuditableEntity, IExternalId, IHistoryTracked
{
    /// <summary>
    /// Foreign-key reference to the owning <see cref="Contributor"/> whose
    /// outstanding obligation this claim represents.
    /// </summary>
    public long ContributorId { get; set; }

    /// <summary>
    /// Externally-stable claim identifier in the format
    /// <c>CRN-{year}-{seq:000000}</c> (e.g. <c>CRN-2026-000001</c>). Generated
    /// server-side at registration time; unique across the registry.
    /// </summary>
    public required string ClaimNumber { get; set; }

    /// <summary>
    /// Reporting month the claim relates to (day = 1 by convention) — typically
    /// the month of the unpaid contribution. Validators enforce <c>Day == 1</c>
    /// before persistence.
    /// </summary>
    public DateOnly RelatedMonth { get; set; }

    /// <summary>
    /// Classification of the claim — drives reporting bucketing and downstream
    /// routing (e.g. late-penalty differential vs. court-ordered assessment).
    /// </summary>
    public ClaimKind Kind { get; set; }

    /// <summary>
    /// Original outstanding amount owed (MDL). Immutable in the sense that
    /// modifications are only allowed via <c>ModifyAsync</c> with a rationale;
    /// the audit trail captures the change.
    /// </summary>
    public decimal PrincipalAmount { get; set; }

    /// <summary>
    /// Running total of payments received against this claim (MDL). Sum of
    /// <see cref="ClaimPayment.Amount"/> across non-deleted payment rows.
    /// </summary>
    public decimal PaidAmount { get; set; }

    /// <summary>
    /// Computed/cached remainder owed (MDL): <see cref="PrincipalAmount"/> −
    /// <see cref="PaidAmount"/>. Materialised on the row so reporting queries
    /// can filter <c>WHERE RemainingAmount > 0</c> without a subquery.
    /// </summary>
    public decimal RemainingAmount { get; set; }

    /// <summary>
    /// Lifecycle status — defaults to <see cref="ClaimStatus.Open"/>. The
    /// service mutates this field as payments accumulate or admins cancel /
    /// dispute the claim.
    /// </summary>
    public ClaimStatus Status { get; set; } = ClaimStatus.Open;

    /// <summary>Date the claim was opened (entered into the registry).</summary>
    public DateOnly OpenedDate { get; set; }

    /// <summary>
    /// Optional administrative deadline by which the claim should be settled
    /// (e.g. payment plan target). Null when no deadline applies.
    /// </summary>
    public DateOnly? DueDate { get; set; }

    /// <summary>
    /// Date the claim was fully settled (running total reached
    /// <see cref="PrincipalAmount"/>). Null while the claim remains
    /// outstanding.
    /// </summary>
    public DateOnly? SettledDate { get; set; }

    /// <summary>
    /// Date the claim was cancelled by an admin. Null while the claim is
    /// active.
    /// </summary>
    public DateOnly? CancelledDate { get; set; }

    /// <summary>
    /// Operator-supplied rationale for the cancellation (3..500 chars when set).
    /// Null while the claim is not cancelled.
    /// </summary>
    public string? CancelReason { get; set; }

    /// <summary>
    /// Optional cross-reference to the source document — court order number,
    /// audit-control report number, late-penalty row id, etc. Free-form text
    /// up to 256 chars.
    /// </summary>
    public string? RelatedDocumentReference { get; set; }
}

/// <summary>
/// R0832 / TOR BP 1.3-C — one payment received against a <see cref="Claim"/>.
/// Partial payments accumulate until the running total reaches the claim's
/// <see cref="Claim.PrincipalAmount"/>, at which point the claim transitions
/// to <see cref="ClaimStatus.Settled"/>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Cascade delete.</b> When a parent <see cref="Claim"/> is hard-deleted (a
/// rare event reserved for data-correction / GDPR scenarios) the payment rows
/// follow. In normal operation claims are soft-deleted via
/// <see cref="AuditableEntity.IsActive"/>, in which case payments remain
/// queryable through the soft-deleted parent for historical reporting.
/// </para>
/// <para>
/// <b>Optional Treasury linkage.</b> <see cref="TreasuryPaymentReceiptId"/>
/// links the payment to the underlying Treasury feed receipt when one exists.
/// Until R0911 auto-allocation lands, operators may register a payment that
/// references a Treasury receipt without the system pre-distributing it.
/// </para>
/// <para>
/// <b>External id.</b> Implements <see cref="IExternalId"/> because the
/// outbound DTO (<c>Cnas.Ps.Contracts.ClaimPaymentDto.Id</c>) carries the
/// Sqid-encoded surrogate per CLAUDE.md RULE 3.
/// </para>
/// </remarks>
public sealed class ClaimPayment : AuditableEntity, IExternalId
{
    /// <summary>
    /// Foreign-key reference to the owning <see cref="Claim"/>. Cascade delete
    /// on hard-delete of the parent.
    /// </summary>
    public long ClaimId { get; set; }

    /// <summary>Calendar date the payment was received.</summary>
    public DateOnly PaidDate { get; set; }

    /// <summary>
    /// Payment amount (MDL). Strictly positive — the validator bounds the
    /// value to (0, 100_000_000]. The service refuses payments that would
    /// drive the claim's running total past <see cref="Claim.PrincipalAmount"/>
    /// with <c>OVERPAYMENT_NOT_ALLOWED</c>.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Optional external payment reference (e.g. Treasury receipt reference
    /// number, bank-transfer reference, MPay order code). Participates in the
    /// unique <c>(ClaimId, PaymentReference)</c> index when non-null so the
    /// same external reference cannot be registered twice against the same
    /// claim.
    /// </summary>
    public string? PaymentReference { get; set; }

    /// <summary>
    /// Optional FK to the underlying <see cref="TreasuryPaymentReceipt"/> row
    /// when the payment was matched against a Treasury feed entry. Null when
    /// the payment was registered manually from another source (bank
    /// transfer, cash, MPay, etc.).
    /// </summary>
    public long? TreasuryPaymentReceiptId { get; set; }

    /// <summary>
    /// Free-form operator notes attached to the payment row (0..1000 chars
    /// when set).
    /// </summary>
    public string? Notes { get; set; }
}
