namespace Cnas.Ps.Core.Domain;

/// <summary>
/// Document — any document generated by SI PS or attached to a Dossier. TOR §2.3 #3.
/// </summary>
/// <remarks>
/// The document's binary content is stored in MinIO; this entity stores metadata and the
/// MinIO object key. Per SEC 010 (OWASP) the content type is validated against magic bytes
/// before storage and a randomised storage filename is used.
/// </remarks>
public sealed class Document : AuditableEntity, IExternalId
{
    /// <summary>FK to the Dossier this document belongs to (nullable for unattached templates).</summary>
    public long? DossierId { get; set; }

    /// <summary>Kind of document — see <see cref="DocumentKind"/>.</summary>
    public DocumentKind Kind { get; set; }

    /// <summary>Display title of the document (printed in the dossier, exported in lists).</summary>
    public required string Title { get; set; }

    /// <summary>MIME type as declared by the uploader (validated against magic bytes).</summary>
    public required string MimeType { get; set; }

    /// <summary>Size in bytes; capped by configuration (SEC 010).</summary>
    public long SizeBytes { get; set; }

    /// <summary>MinIO object key (random name; never exposes original filename).</summary>
    public required string StorageObjectKey { get; set; }

    /// <summary>MinIO bucket where the object lives. Defaults to per-tenant bucket.</summary>
    public required string StorageBucket { get; set; }

    /// <summary>SHA-256 hex digest of the content (for integrity verification).</summary>
    public required string ContentSha256Hex { get; set; }

    /// <summary>True when the document has been electronically signed via MSign.</summary>
    public bool IsSigned { get; set; }

    /// <summary>Detached signature object key (MinIO) when <see cref="IsSigned"/> is true.</summary>
    public string? SignatureObjectKey { get; set; }

    /// <summary>
    /// UC08 — Examiner's verdict on this attached document. <see langword="null"/> until
    /// the examiner has reviewed it; one of the <c>ExaminationVerdict</c> values (defined
    /// in the Application layer) once recorded. Stored as the underlying <see cref="int"/>
    /// via <c>HasConversion&lt;int&gt;()</c>. The cref is intentionally a string because the
    /// Core layer cannot reference Application types without violating layer boundaries.
    /// </summary>
    public int? Verdict { get; set; }

    /// <summary>Optional free-text note attached to the verdict.</summary>
    public string? VerdictNote { get; set; }

    /// <summary>UTC timestamp at which the examiner recorded the verdict.</summary>
    public DateTime? VerdictAtUtc { get; set; }
}
