namespace Cnas.Ps.Core.Domain;

/// <summary>
/// R1201 / R1402 / TOR §3.4-B / §3.6-C — one international-agreements
/// review case driven through the reusable 3-level routing chain
/// (Local office → Regional office → National / CNAS HQ). The same
/// aggregate backs both the incapacity / maternity benefit (R1201) and the
/// unemployment benefit (R1402); the <see cref="BenefitKind"/> discriminator
/// selects the per-benefit routing policy (role codes + evidence schema).
/// </summary>
/// <remarks>
/// <para>
/// <b>Lifecycle.</b> <see cref="IntlAgreementReviewCaseStatus.Draft"/> →
/// <see cref="IntlAgreementReviewCaseStatus.AtLocalReview"/> (via
/// <c>SubmitAsync</c>) → <see cref="IntlAgreementReviewCaseStatus.AtRegionalReview"/>
/// → <see cref="IntlAgreementReviewCaseStatus.AtNationalReview"/> →
/// <see cref="IntlAgreementReviewCaseStatus.Approved"/> when every level
/// approves. Any reviewer can <c>Reject</c> (terminal) or
/// <c>RequestRevision</c> (state flips to
/// <see cref="IntlAgreementReviewCaseStatus.RevisionRequested"/>; the
/// requester can <c>Resubmit</c> to re-enter the chain from level 1).
/// Operators may <c>Cancel</c> any non-terminal case.
/// </para>
/// <para>
/// <b>Encrypted column.</b> <see cref="BeneficiaryIdnp"/> is encrypted at
/// rest via <c>EncryptedStringConverter</c> (CLAUDE.md §5.7). Equality
/// lookups go through the deterministic HMAC shadow column
/// <see cref="BeneficiaryIdnpHash"/>.
/// </para>
/// <para>
/// <b>External id.</b> Implements <see cref="IExternalId"/> because the
/// outbound DTO carries a Sqid-encoded surrogate per CLAUDE.md RULE 3.
/// </para>
/// </remarks>
public sealed class IntlAgreementReviewCase : AuditableEntity, IExternalId
{
    /// <summary>
    /// Stable external identifier, auto-generated by the service in the
    /// format <c>IAR-{year}-{seq:000000}</c>. Unique across the registry;
    /// capped at 32 characters at the persistence layer.
    /// </summary>
    public required string CaseNumber { get; set; }

    /// <summary>Benefit kind discriminator — selects the per-benefit routing policy.</summary>
    public IntlAgreementBenefitKind BenefitKind { get; set; }

    /// <summary>
    /// Moldovan personal-numeric-identifier (IDNP, 13 digits) of the
    /// beneficiary. Encrypted at rest per CLAUDE.md §5.7; equality lookups
    /// go through <see cref="BeneficiaryIdnpHash"/>.
    /// </summary>
    public required string BeneficiaryIdnp { get; set; }

    /// <summary>
    /// Base64-encoded HMAC-SHA256 hash of the canonicalised
    /// <see cref="BeneficiaryIdnp"/> (44 chars including <c>=</c> padding).
    /// Backs equality lookups and the duplicate-detection index. Maintained
    /// by the application layer via <c>IDeterministicHasher</c>.
    /// </summary>
    public required string BeneficiaryIdnpHash { get; set; }

    /// <summary>Display name of the beneficiary (3..256 chars). Treated as Internal sensitivity.</summary>
    public required string BeneficiaryDisplayName { get; set; }

    /// <summary>
    /// Stable code for the bilateral agreement that frames this case (e.g.
    /// <c>RO_MD_2006</c>, <c>DE_MD_2018</c>, <c>TR_MD_2014</c>). Validator
    /// enforces the regex <c>^[A-Z]{2}_MD_\d{4}$</c>. Capped at 64 chars.
    /// </summary>
    public required string AgreementCode { get; set; }

    /// <summary>
    /// ISO-3166 alpha-2 uppercase host-country code (e.g. <c>RO</c>,
    /// <c>DE</c>, <c>TR</c>). Exactly 2 chars; validated at the boundary.
    /// </summary>
    public required string HostCountryCode { get; set; }

    /// <summary>Lifecycle status. Drives the state-machine guard at every service entry point.</summary>
    public IntlAgreementReviewCaseStatus Status { get; set; } = IntlAgreementReviewCaseStatus.Draft;

    /// <summary>Current routing level. Matches the reviewer-role check at every <c>RecordReviewAsync</c>.</summary>
    public IntlAgreementReviewLevel CurrentLevel { get; set; } = IntlAgreementReviewLevel.Local;

    /// <summary>
    /// Optional Sqid of the parent benefit passport (sick-leave passport,
    /// unemployment passport, etc.) — a stable opaque pointer carried for
    /// cross-registry navigation. Capped at 32 chars.
    /// </summary>
    public string? ReferenceBenefitPassportSqid { get; set; }

    /// <summary>UTC timestamp the case entered <see cref="IntlAgreementReviewCaseStatus.AtLocalReview"/>.</summary>
    public DateTime? SubmittedAt { get; set; }

    /// <summary>UTC timestamp the case was approved (all 3 levels cleared).</summary>
    public DateTime? ApprovedAt { get; set; }

    /// <summary>UTC timestamp the case was rejected by a reviewer.</summary>
    public DateTime? RejectedAt { get; set; }

    /// <summary>Reviewer-supplied rejection rationale (mirrors the step note; 3..1000 chars).</summary>
    public string? RejectionReason { get; set; }

    /// <summary>UTC timestamp the case entered <see cref="IntlAgreementReviewCaseStatus.RevisionRequested"/>.</summary>
    public DateTime? RevisionRequestedAt { get; set; }

    /// <summary>Reviewer-supplied revision-request note (mirrors the step note; 3..1000 chars).</summary>
    public string? RevisionRequestNote { get; set; }

    /// <summary>UTC timestamp the case was cancelled (terminal).</summary>
    public DateTime? CancelledAt { get; set; }

    /// <summary>Operator-supplied cancellation rationale (3..1000 chars).</summary>
    public string? CancelReason { get; set; }

    /// <summary>FK to the <see cref="UserProfile"/> who created the case.</summary>
    public int RegisteredByUserId { get; set; }

    /// <summary>
    /// JSON-encoded supporting evidence envelope. The shape is validated by
    /// the per-benefit-kind routing policy. NEVER contains PII — only
    /// stable codes + numerics + opaque document references. Capped at
    /// 16 384 chars at the persistence layer.
    /// </summary>
    public string? EvidenceJson { get; set; }
}
