namespace Cnas.Ps.Core.Domain;

/// <summary>
/// Persisted record of an MPay payment order originated by CNAS. Each row models the
/// life-cycle of a single citizen payment ceremony:
/// <list type="number">
///   <item>The CNAS-side service mints an opaque <see cref="OrderId"/> and inserts a row
///   with <see cref="PaymentRef"/> = <c>null</c> and <see cref="ConfirmedAtUtc"/> =
///   <c>null</c> immediately before posting the order to MPay
///   (<c>IMPayClient.PostOrderAsync</c>).</item>
///   <item>The citizen pays through the MPay portal. MPay calls
///   <c>GET /api/mpay/orders/{orderId}/details</c> to quote the amount + descriptor; the
///   controller serves the data from this row.</item>
///   <item>Once payment settles MPay calls
///   <c>POST /api/mpay/orders/{orderId}/confirm</c>; the controller stamps
///   <see cref="PaymentRef"/> + <see cref="ConfirmedAtUtc"/> on this row. Idempotent —
///   a retried POST with the same <c>(orderId, paymentRef)</c> tuple is a no-op
///   (CLAUDE.md cross-cutting "Idempotent Callbacks", red-flag #15).</item>
/// </list>
/// </summary>
/// <remarks>
/// <para>
/// <b>Identifier convention.</b> <see cref="OrderId"/> is the CNAS-side stable business
/// identifier MPay uses to refer back to the order — it appears in the route segment of
/// every callback. CLAUDE.md RULE 3 (Sqid-encode external IDs) does NOT apply to this
/// field: the MPay wire contract requires the same string we issued on
/// <c>PostOrderAsync</c> verbatim, so Sqid-encoding would break the contract. The
/// surrogate <see cref="AuditableEntity.Id"/> stays internal and never leaves the
/// system.
/// </para>
/// <para>
/// <b>IDNP encryption.</b> The <see cref="BeneficiaryIdnp"/> column carries the citizen's
/// 13-digit IDNP — PII per TOR SEC 035. The application-level encryption seam used by
/// <see cref="Solicitant.NationalId"/> and <see cref="InsuredPerson.Idnp"/> is the
/// natural fit here. TODO[encrypt-mpay-idnp]: wire this column through
/// <c>EncryptedStringConverter</c> in <c>CnasDbContext.OnModelCreating</c> once B1 SAML
/// integration lands and this table starts carrying production IDNPs. Until then the
/// column is plaintext at rest — A2 batch persists only legacy-shim placeholder values
/// because no production citizen payment flow exercises the table yet.
/// </para>
/// <para>
/// <b>Soft-delete + audit.</b> Inherits the standard auditing fields
/// (<see cref="AuditableEntity.CreatedAtUtc"/>, <see cref="AuditableEntity.UpdatedAtUtc"/>,
/// <see cref="AuditableEntity.IsActive"/>, <see cref="AuditableEntity.Xmin"/>) from
/// <see cref="AuditableEntity"/>. Logical deletion clears <see cref="AuditableEntity.IsActive"/>
/// rather than removing the row so the audit trail of dispatched payments stays intact.
/// </para>
/// </remarks>
public sealed class MPayOrder : AuditableEntity
{
    /// <summary>
    /// CNAS-side stable order identifier. Generated by the service layer immediately
    /// before <c>IMPayClient.PostOrderAsync</c>; reused verbatim on every MPay callback
    /// (<c>GET .../details</c> and <c>POST .../confirm</c>). Unique across all rows
    /// (enforced by an index on the EF configuration). NOT Sqid-encoded — see the
    /// class-level remarks for the RULE 3 exception.
    /// </summary>
    public required string OrderId { get; set; }

    /// <summary>
    /// Total amount the citizen will be charged, in Moldovan Lei. Stored at
    /// <c>decimal(18, 2)</c> precision to match the rest of the financial columns in the
    /// schema. Captured at <c>PostOrderAsync</c> time and never mutated — the confirmed
    /// amount is whatever the original order quoted, so a successful confirmation does
    /// not need to write this field.
    /// </summary>
    public decimal AmountMdl { get; set; }

    /// <summary>
    /// Romanian payment descriptor shown to the citizen on the MPay payment page. Echoed
    /// back to MPay verbatim by the <c>GET .../details</c> endpoint. Single-line free
    /// text; the service layer applies no special characters policy because the upstream
    /// portal owns the rendering.
    /// </summary>
    public required string DescriptionRo { get; set; }

    /// <summary>
    /// 13-digit IDNP of the citizen the payment is bound to. PII — see the class-level
    /// remarks for the encryption-seam TODO. Echoed back to MPay verbatim by the
    /// <c>GET .../details</c> endpoint so the portal can pre-fill the payer identity.
    /// Never logged.
    /// </summary>
    public required string BeneficiaryIdnp { get; set; }

    /// <summary>
    /// Upstream bank / processor transaction id, as supplied by MPay on the confirm
    /// callback. <c>null</c> until the citizen settles payment. A retried confirm with
    /// the same value is idempotent (no-op success); a retried confirm with a DIFFERENT
    /// value on an already-confirmed row is a conflict (<see cref="Cnas.Ps.Core.Common.ErrorCodes.Conflict"/>)
    /// — never silently overwrite.
    /// </summary>
    public string? PaymentRef { get; set; }

    /// <summary>
    /// UTC instant at which MPay recorded the citizen's payment as settled. <c>null</c>
    /// while the order is still pending. Set in the same write that populates
    /// <see cref="PaymentRef"/>. Together the two fields form the row's
    /// "confirmed" state.
    /// </summary>
    public DateTime? ConfirmedAtUtc { get; set; }

    /// <summary>
    /// R1504 / TOR §3.7-E — CNAS-initiated suspension flag. When <c>true</c> the
    /// dispatcher MUST NOT post this order to MPay (and any in-flight ceremony
    /// is treated as paused). Flipped back to <c>false</c> by the resume
    /// workflow. Default <c>false</c> for back-compat with existing rows.
    /// </summary>
    public bool IsSuspended { get; set; }

    /// <summary>
    /// R1504 / TOR §3.7-E — UTC instant the order was most recently suspended.
    /// <c>null</c> when the order has never been suspended; carries the latest
    /// suspension instant when <see cref="IsSuspended"/> is <c>true</c>; retains
    /// the prior value after resume for forensic lookups.
    /// </summary>
    public DateTime? SuspendedAtUtc { get; set; }
}
