{{/*
=============================================================================
PVC claim template (snippet used by the Postgres StatefulSet).
=============================================================================
NOTE: this file has the `.tpl` suffix so Helm treats it as a partial /
include rather than a standalone manifest. It is referenced symbolically
from postgres-statefulset.yaml's `volumeClaimTemplates` (the STS embeds
this exact shape inline). The standalone file exists to document the
PVC contract independently — operators reviewing storage policy can read
THIS file without parsing the full StatefulSet.

The claim template carries:
  * accessModes: [ReadWriteOnce] — Postgres needs an exclusive block
    device. RWX would let two pods mount the same volume, which is
    fatal for Postgres (the second pod would corrupt the data dir).
  * storageClassName: from values.postgres.storageClass. Empty value
    means "cluster default StorageClass" — acceptable for dev, NOT for
    production (default classes often have unspecified retention policy).
  * resources.requests.storage: 100Gi default. Postgres datadir
    rough-sizing: 1 GB per million tuples in the largest table, plus
    WAL (typically 2 GB) and the catalog (~200 MB).

DO NOT edit this file expecting it to render — it is documentation. The
operative claim template lives inline in postgres-statefulset.yaml.
=============================================================================
*/}}
{{- define "cnas-ps.postgresPvcClaim" -}}
- metadata:
    name: data
    labels:
      {{ include "cnas-ps.componentLabels" (dict "ctx" . "component" "postgres") | nindent 6 }}
  spec:
    accessModes: ["ReadWriteOnce"]
    {{- if .Values.postgres.storageClass }}
    storageClassName: {{ .Values.postgres.storageClass | quote }}
    {{- end }}
    resources:
      requests:
        storage: {{ .Values.postgres.storageSize }}
{{- end -}}
