using Cnas.Ps.Application.Exports;
using Cnas.Ps.Infrastructure.Exports;

namespace Cnas.Ps.Infrastructure.Tests.Exports;

/// <summary>
/// R0226 / TOR UI 013 — happy-path tests for <see cref="PdfGridExportRenderer"/>.
/// Verifies the renderer emits a real PDF byte stream (PDF magic) and that the
/// content-type / filename surface match the PDF conventions.
/// </summary>
public sealed class PdfGridExportRendererTests
{
    [Fact]
    public async Task RenderAsync_HappyPath_ReturnsPdfMime_AndPdfMagic()
    {
        var sut = new PdfGridExportRenderer();
        var request = new GridExportRequest(
            GridName: "Solicitants",
            Columns: new GridColumn[]
            {
                new("Code", "Code", GridColumnDataType.Text),
                new("Name", "Name", GridColumnDataType.Text),
            },
            Rows: new GridRow[]
            {
                new(new Dictionary<string, object?>
                {
                    ["Code"] = "SQID-1",
                    ["Name"] = "Ion",
                }),
            },
            Title: "Solicitants export",
            FooterNote: "Generated by CNAS",
            Language: "ro");

        var result = await sut.RenderAsync(request);

        result.IsSuccess.Should().BeTrue();
        result.Value.ContentType.Should().Be("application/pdf");
        // Every PDF starts with the literal bytes "%PDF-".
        var head = System.Text.Encoding.ASCII.GetString(result.Value.Content, 0, 5);
        head.Should().Be("%PDF-");
    }
}
